name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to container registry
        env: 
         PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: echo $PUSH_TOKEN | docker login ghcr.io -u USERNAME --password-stdin       
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run:  chmod +x ./buildPush.sh && ./buildPush.sh
